excluded:
  - MHA_CompanionTests/

disabled_rules:
  - multiple_closures_with_trailing_closure
  - type_name
  - switch_case_alignment

line_length: 150

identifier_name:
  excluded:
    - id
    - _self
